SET TIME ZONE 'UTC';

BEGIN;

CREATE TABLE shortened_urls (
    full_url TEXT NOT NULL,
    short_url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expire TIMESTAMP NOT NULL
);

COMMIT;